backend:
  name: git-gateway
  branch: netlify-cms-support

media_folder: "images/uploads"

collections:
  - label: "Overrides"
    name: "overrides"
    files:
      - label: "Beerbods overrides"
        name: "overrides"
        file: "overrides.json"
        fields:
          - label: Untappd Manual Lookups
            name: beerbodsUntappdId
            widget: list
            fields:
              - {label: Beerbods Name, name: beerbodsName, widget: string}
              - {label: Untappd ID, name: untappdId, widget: number, valueType: int}
          - label: Beerbods Name Overrides
            name: beerbodsUntappdId
            widget: list
            fields:
              - {label: Beerbods Page Name, name: beerbodsName, widget: string}
              - {label: Name to use instead, name: overrideName, widget: string}
