backend:
  name: git-gateway
  branch: master

media_folder: images/uploads

collections:
  - label: Beerbods Untappd Mapping
    name: beerbods untappd mapping
    files:
      - label: Untappd Mappings
        name: overrides
        file: untappd-mapping.json
        fields:
          - label: Untappd Manual Mapping
            name: beerbodsUntappdId
            widget: list
            fields:
              - {label: Beerbods Name, name: beerbodsName, widget: string, required: true}
              - {label: Untappd ID, name: untappdId, widget: number, valueType: int, required: true}
  - label: Name Override
    name: name override
    files:
      - label: Name Overrides
        name: nameoverrides
        file: name-overrides.json
        fields:
          - label: Beerbods Name Override
            name: beerbodsNameOverride
            widget: list
            fields:
              - {label: Beerbods Page Name, name: beerbodsName, widget: string}
              - label: Override Names
                name: names
                widget: list
                fields:
                  - {label: Name to use instead, name: overrideName, widget: string}
